require: rubocop-rake
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - "**/emsdk/**/*"
    - "**/node_modules/**/*"
    - "**/target/**/*"
    - "**/vendor/**/*"
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
