---
require: rubocop-rake
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - "**/emsdk/**/*"
    - "**/node_modules/**/*"
    - "**/target/**/*"
    - "**/vendor/**/*"
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Enabled: true
  Exclude:
    - "**/Rakefile"
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
