[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-DFS-2016",
]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "warn" # multiple versions of syn and windows-sys as ecosystem converges
wildcards = "deny"
highlight = "all"
allow = []
deny = [
  { name = "time", version = ">=0.2.0" },
]
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[sources.allow-org]
github = [
  "artichoke",
]
