[package]
name = "playground"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"

[dependencies.artichoke-backend]
git = "https://github.com/artichoke/artichoke"
rev = "7ccb426ef8a7c4656ee0d24b3a31c5f65a9a08c9"
default-features = false

[dependencies.artichoke-core]
git = "https://github.com/artichoke/artichoke"
rev = "7ccb426ef8a7c4656ee0d24b3a31c5f65a9a08c9"

[build-dependencies]
rustc_version = "0.2.3"
