[package]
name = "playground"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"

[dependencies.artichoke-backend]
git = "https://github.com/artichoke/artichoke"
rev = "6657c0970b00c60ee268e84ed1bccde40c7e2ac0"
default-features = false
features = ["artichoke-array", "artichoke-random"]

[dependencies.artichoke-core]
git = "https://github.com/artichoke/artichoke"
rev = "6657c0970b00c60ee268e84ed1bccde40c7e2ac0"

[build-dependencies]
rustc_version = "0.2.3"
