[package]
name = "playground"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"

[dependencies]
bstr = { version = "0.2", default-features = false }

[dependencies.artichoke]
git = "https://github.com/artichoke/artichoke.git"
rev = "87b25941224b098f4f0daed7443116acb3972223"
default-features = false
features = [
  "core-env",
  "core-math-full",
  "core-random",
  "output-strategy-capture",
  "stdlib-securerandom"
]
