[package]
name = "playground"
version = "0.2.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/artichoke/playground"
homepage = "https://artichoke.run"
description = """
The Artichoke Playground is a WebAssembly frontend for Artichoke Ruby hosted at
https://artichoke.run.
"""
keywords = ["artichoke", "artichoke-ruby", "playground", "ruby", "wasm"]
categories = ["emulators", "wasm", "web-programming"]

[dependencies]
bstr = { version = "0.2", default-features = false }

[dependencies.artichoke]
git = "https://github.com/artichoke/artichoke.git"
rev = "87b25941224b098f4f0daed7443116acb3972223"
default-features = false
features = [
  "core-env",
  "core-math-full",
  "core-random",
  "output-strategy-capture",
  "stdlib-securerandom"
]
