[package]
name = "playground"
version = "0.4.0" # remember to bump package.json
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/artichoke/playground"
homepage = "https://artichoke.run"
description = """
The Artichoke Playground is a WebAssembly frontend for Artichoke Ruby hosted at
https://artichoke.run.
"""
keywords = ["artichoke", "artichoke-ruby", "playground", "ruby", "wasm"]
categories = ["emulators", "wasm", "web-programming"]

[dependencies]
bstr = { version = "0.2, >= 0.2.4", default-features = false }

[dependencies.artichoke]
version = "0.1.0-pre.0"
git = "https://github.com/artichoke/artichoke.git"
rev = "5b0b0e54cafd465008822e809d979e8b5c23d43c"
default-features = false
features = [
  "core-env",
  "core-math",
  "core-math-full",
  "core-random",
  "core-regexp",
  "output-strategy-capture",
  "stdlib-full",
]
