name: Audit
on: [push]
jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node toolchain
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Nodejs toolchain
        run: yarn install --frozen-lockfile

      - name: Yarn audit
        run: yarn audit
