---
name: CI
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  build-rust:
    name: Build Rust
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set toolchain versions
        run: |
          echo "rust=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
          echo "emscripten=$(cat emscripten-toolchain)" >> $GITHUB_OUTPUT
        id: toolchain_versions

      - name: Install Rust toolchain
        run: |
          echo "::group::rustup toolchain install"
          rustup toolchain install ${{ steps.toolchain_versions.outputs.rust }} --profile minimal
          echo "::endgroup::"
          echo "::group::rustup version"
          rustup -Vv
          echo "::endgroup::"
          echo "::group::rustc version"
          rustc -Vv
          echo "::endgroup::"
          echo "::group::cargo version"
          cargo version --verbose
          echo "::endgroup::"

      - uses: Swatinem/rust-cache@v2

      - name: Compile
        run: cargo build --workspace --verbose

      - name: Compile tests
        run: cargo test --workspace --no-run

      - name: Test
        run: cargo test --workspace

  build-webapp:
    name: Build Webapp
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set toolchain versions
        run: |
          echo "rust=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
          echo "emscripten=$(cat emscripten-toolchain)" >> $GITHUB_OUTPUT
        id: toolchain_versions

      - name: Install Node.js toolchain
        uses: actions/setup-node@v3
        with:
          node-version: 19 # todo switch to LTS when it ships npm 9

      - name: Install Rust toolchain
        run: |
          echo "::group::rustup toolchain install"
          rustup toolchain install ${{ steps.toolchain_versions.outputs.rust }} --profile minimal --target wasm32-unknown-emscripten
          echo "::endgroup::"
          echo "::group::rustup version"
          rustup -Vv
          echo "::endgroup::"
          echo "::group::rustc version"
          rustc -Vv
          echo "::endgroup::"
          echo "::group::cargo version"
          cargo version --verbose
          echo "::endgroup::"

      - uses: Swatinem/rust-cache@v2

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Install Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ steps.toolchain_versions.outputs.emscripten }}
          no-cache: true

      - name: Verify emcc version
        run: emcc -v

      - name: Install Nodejs toolchain
        run: npm ci

      - name: Compile Wasm
        run: ruby scripts/build-wasm.rb --release --verbose

      - name: Build Webapp
        run: node build.mjs --release

  rust:
    name: Lint and format Rust
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set toolchain versions
        run: |
          echo "rust=$(cat rust-toolchain)" >> $GITHUB_OUTPUT
          echo "emscripten=$(cat emscripten-toolchain)" >> $GITHUB_OUTPUT
        id: toolchain_versions

      - name: Install Rust toolchain
        run: |
          echo "::group::rustup toolchain install"
          rustup toolchain install ${{ steps.toolchain_versions.outputs.rust }} --profile minimal --target wasm32-unknown-emscripten --component rustfmt clippy
          echo "::endgroup::"
          echo "::group::rustup version"
          rustup -Vv
          echo "::endgroup::"
          echo "::group::rustc version"
          rustc -Vv
          echo "::endgroup::"
          echo "::group::cargo version"
          cargo version --verbose
          echo "::endgroup::"

      - uses: Swatinem/rust-cache@v2

      - name: Install Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ steps.toolchain_versions.outputs.emscripten }}

      - name: Verify emcc version
        run: emcc -v

      - name: Check formatting
        run: cargo fmt --check

      - name: Lint with Clippy
        run: cargo clippy --workspace --all-features --all-targets

      - name: Lint with Clippy on emscripten target
        run: cargo clippy --workspace --all-features --all-targets --target wasm32-unknown-emscripten

  ruby:
    name: Lint and format Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Lint and check formatting with Rubocop
        run: bundle exec rubocop --format github

  js-ts:
    name: Lint and format JavaScript and TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nodejs toolchain
        run: npm ci

      - name: Create stubs for Wasm Sources
        run: |
          touch src/wasm/playground.js
          touch src/wasm/playground.wasm

      - name: Compile with TypeScript
        run: npx tsc --extendedDiagnostics --listFiles --listEmittedFiles

      - name: Lint with eslint
        run: npm run lint

  text:
    name: Lint and format text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint and check formatting with prettier
        run: npx prettier --check '**/*'

      - name: Lint YAML sources with yamllint
        run: |
          yamllint --version
          echo "Linting YAML sources with yamllint ..."
          yamllint --strict --format github .
          echo "OK"
