name: Playground
on: [push]
jobs:
  wasm:
    name: Build Playground
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-emscripten
          profile: minimal
          override: true

      - name: Install Ruby toolchain
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: Install Clang
        run: sudo apt install clang

      - name: Install Bison
        run: sudo apt install bison

      - name: Install Emscripten toolchain
        run: |
          git clone https://github.com/emscripten-core/emsdk.git emsdk
          ./emsdk/emsdk install "$(cat emscripten-toolchain)"
          ./emsdk/emsdk activate "$(cat emscripten-toolchain)"

      - name: Install Node toolchain
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Nodejs toolchain
        run: yarn install --frozen-lockfile

      - name: Compile
        run: |
          . ./emsdk/emsdk_env.sh
          cargo build --target wasm32-unknown-emscripten --release --verbose

      - name: Webpack build
        run: yarn webpack --mode production

      - name: Copy static content
        run: cp assets/* target/dist

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/dist
          publish_branch: gh-pages
          user_name: artichoke-ci
          user_email: ci@artichokeruby.org
