name: Playground
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * TUE"
jobs:
  wasm:
    name: Build Playground
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-emscripten
          profile: minimal
          override: true

      - name: Install Ruby toolchain
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: Install Clang
        run: sudo apt install clang

      - name: Install Bison
        run: sudo apt install bison

      - name: Set emsdk version
        run: echo "::set-output name=version::$(cat emscripten-toolchain)"
        id: emsdk_toolchain

      - name: Install Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v2
        with:
          version: ${{ steps.emsdk_toolchain.outputs.version }}

      - name: Install Nodejs toolchain
        run: npm ci

      - name: Compile
        run: cargo build --target wasm32-unknown-emscripten --release --verbose
        env:
          RUSTFLAGS: "-C link-arg=-s -C link-arg=MODULARIZE=1"

      - name: Webpack build
        run: npx webpack --mode production

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/dist
          publish_branch: gh-pages
          user_name: artichoke-ci
          user_email: ci@artichokeruby.org
